---
- name: Configuring AAA
  hosts: SW2
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_python_interpreter: python3
    ansible_user: admin
    ansible_password: admin
    timeout: 100

  tasks:
  - name:  AAA Global Config
    ios_config:
      lines:
      - aaa new-model
      - aaa authentication login default local
      - aaa authorization exec default local

      save_when: modified

    register: print_output
      
  - debug: var=print_output
       