- name: Configuring OSPF for R5
  hosts: R5
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_python_interpreter: python3
    ansible_user: admin
    ansible_password: admin
    timeout: 100  
 
  tasks:
  - name: Global Config Ospf for R5
    ios_config:
      lines:
        - router ospf 65000
        - router-id 5.5.5.5
        - passive-interface default
        - no passive-interface fa1/0
        - network 5.5.5.5 0.0.0.0 area 0
        - network 169.10.10.44 0.0.0.3 area 0
          
      parents: router ospf 65000
      save_when: modified  

    register: print_output
      
  - debug: var=print_output
  
- name: Configuring OSPF for R6
  hosts: R6
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_python_interpreter: python3
    ansible_user: admin
    ansible_password: admin
    timeout: 100 
  
  tasks:  
  - name: Global Config Ospf for R6
    ios_config:
      lines:
        - router ospf 65000
        - router-id 6.6.6.6
        - passive-interface default
        - no passive-interface fa1/0
        - network 6.6.6.6 0.0.0.0 area 0
        - network 169.10.10.48 0.0.0.3 area 0
          
      parents: router ospf 65000
      save_when: modified

    register: print_output
      
  - debug: var=print_output

- name: Configuring OSPF for SW2
  hosts: SW2
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_python_interpreter: python3
    ansible_user: admin
    ansible_password: admin
    timeout: 100 
  
  tasks:
  - name: Configuring the Ethernet0/1
    ios_config:
      lines:
        - description ^P2P to R5
        - duplex full
        - ip address 169.10.10.46 255.255.255.252
        - no shutdown

      parents: interface ethernet0/1
      save_when: modified

  - name: Configuring the Ethernet0/2
    ios_config:
      lines:
        - description ^P2P to 
        - duplex full
        - ip address 169.10.10.50 255.255.255.252
        - no shutdown

      parents: interface ethernet0/2
      save_when: modified

  - name: Configuring the Loopback0
    ios_config:
      lines:
        - interface loopback0
        - ip address 8.8.8.8 255.255.255.255
        - no shutdown

      save_when: modified

  - name: Global Config Ospf for R6
    ios_config:
      lines:
        - router ospf 65000
        - router-id 8.8.8.8
        - passive-interface default
        - no passive-interface e0/1
        - no passive-interface e0/2
        - network 8.8.8.8 0.0.0.0 area 0
        - network 169.10.10.44 0.0.0.3 area 0
        - network 169.10.10.48 0.0.0.3 area 0
          
      parents: router ospf 65000
      save_when: modified

    register: print_output
      
  - debug: var=print_output